tickers:
  - VHM
  - VIC
  - HPG
  - VCB
  - SAB
  - GAS
  - BID
  - CTG
  - MSN
  - NVL
  - PLX
  - HDB
  - VRE
  - BVL
  - FPT
  - ACB
  - TPB
  - EIB
  - SSI
  - SSB
  - REE
  - TCB
  - TNG
  - VCG
  - MWG
  - KDH
  - VCI
  - BVH
  - HSG
  - POW

